spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
    username: postgres
    password: lalala
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
